log:
  level: debug
  target: stdout|fileout
  sync: true
epoll:
  event_size: 4096
tcp:
  host: 127.0.0.1
  port: 12000
  send_timeout: 1000
  recv_timeout: 500
udp:
  host: 127.0.0.1
  port: 12500
  disconnection_timeout_ms: 3000
redis:
  redis_count: 6
  redis_host: 127.0.0.1
  redis_port: 6379
  redis_auth: 123456
worker:
  io_worker_num: 4
  process_worker_num: 4